services:
  - type: web
    name: tenantforge
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: TenantForge
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false # Generate locally with `php artisan key:generate --show` and set in Render Dashboard
      - key: APP_URL
        sync: false # e.g. https://laravel-multi-tenant-saas-starter.onrender.com
      - key: CENTRAL_DOMAIN
        sync: false # e.g. laravel-multi-tenant-saas-starter.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: cookie
      - key: MAIL_MAILER
        value: log
      - key: RUN_MIGRATIONS
        value: "true"
      - key: CADDY_GLOBAL_OPTIONS
        value: "auto_https off"
